/* eslint-disable @next/next/no-html-link-for-pages, @typescript-eslint/no-unused-vars */
import { Bell, CalendarDays, CheckCircle2, ChevronDown, CircleAlert, MapPin, Search, Star, TrendingUp, Users, Wrench } from "lucide-react";
import { AccountSidebar } from "./AccountSidebar";
import { prisma } from "@/lib/prisma";
import { requireSession, type AppRole } from "@/lib/auth";
import { AvailabilityToggle } from "./AvailabilityToggle";
import { WorkerEarningsPanel } from "./WorkerEarningsPanel";
import { AccountMenu } from "./AccountMenu";
import { PortalRefreshButton } from "./PortalRefreshButton";
import { getSidebarBadges } from "@/lib/sidebar-badges";
import { normalizePortalLanguage, portalText } from "@/lib/portal-i18n";
import Link from "next/link";
import type { Prisma } from "@prisma/client";

type Role = "customer" | "worker" | "admin";
type RequestRow = { id: string; status: string; description: string; service: { name: string }; updatedAt: Date };
type Notice = { id: string; title: string; body: string; createdAt: Date };

const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
const dateLabel = (date: Date, language = "en") => new Intl.DateTimeFormat(language === "hi" ? "hi-IN" : "en-IN", { day: "2-digit", month: "short" }).format(date);

export async function PortalDashboard({ role, panel }: { role: Role; panel?: string }) {
  const session = await requireSession([role.toUpperCase() as AppRole]);
    const badges = await getSidebarBadges(session.role, session.userId);
  const user = await prisma.user.findUnique({ where: { id: session.userId }, include: { customerProfile: true, workerProfile: true } });
  const language = normalizePortalLanguage(user?.preferredLanguage);
  const name = role === "admin" ? user?.displayName || user?.email.split("@")[0] || "Administrator" : role === "worker" ? user?.workerProfile?.fullName || "Worker account" : user?.customerProfile?.fullName || "Customer account";
  const scope: Prisma.ServiceRequestWhereInput = role === "admin" ? { OR: [{ customer: { user: { status: "ACTIVE" } } }, { worker: { user: { status: "ACTIVE" } } }] } : role === "customer" ? { customer: { userId: session.userId } } : { worker: { userId: session.userId } };
  const [total, active, completed, unread, requests, notices] = await Promise.all([
    prisma.serviceRequest.count({ where: scope }),
    prisma.serviceRequest.count({ where: { ...scope, status: { in: ["SUBMITTED", "SENT", "ACCEPTED", "SCHEDULED", "EN_ROUTE", "IN_PROGRESS"] } } }),
    prisma.serviceRequest.count({ where: { ...scope, status: "COMPLETED" } }),
    prisma.notification.count({ where: { userId: session.userId, readAt: null } }),
    prisma.serviceRequest.findMany({ where: scope, select: { id: true, status: true, description: true, service: { select: { name: true } }, updatedAt: true }, orderBy: { updatedAt: "desc" }, take: 6 }),
    prisma.notification.findMany({ where: { userId: session.userId }, orderBy: { createdAt: "desc" }, take: 5, select: { id: true, title: true, body: true, createdAt: true } }),
  ]);
  const adminData = role === "admin" ? await Promise.all([prisma.user.count({ where: { role: "CUSTOMER", status: "ACTIVE" } }), prisma.user.count({ where: { role: "WORKER", status: "ACTIVE" } }), prisma.workerProfile.count({ where: { availability: "AVAILABLE", user: { status: "ACTIVE" } } }), prisma.workerProfile.findMany({ where: { user: { status: "ACTIVE" } }, orderBy: { completedJobs: "desc" }, take: 5, select: { id: true, fullName: true, completedJobs: true, ratingAverage: true, availability: true } })]) : null;
  const adminPanelRequests = role === "admin" && panel === "requests" ? await prisma.serviceRequest.findMany({ orderBy: { updatedAt: "desc" }, take: 50, select: { id: true, status: true, description: true, locationLabel: true, updatedAt: true, service: { select: { name: true } }, customer: { select: { fullName: true } }, worker: { select: { fullName: true } } } }) : [];
  const workerRating = role === "worker" ? await prisma.review.aggregate({ where: { worker: { userId: session.userId } }, _avg: { rating: true }, _count: { _all: true } }) : null;
  const nearby = role === "customer" ? await prisma.workerProfile.findMany({ where: { availability: "AVAILABLE", user: { status: "ACTIVE" } }, orderBy: { ratingAverage: "desc" }, take: 3, select: { id: true, fullName: true, ratingAverage: true, completedJobs: true } }) : [];
  const title = role === "admin" ? portalText(language, "adminDashboard") : role === "worker" ? portalText(language, "goodMorning", { name }) : portalText(language, "welcomeBack", { name });
  const subtitle = role === "admin" ? portalText(language, "platformOverview") : role === "worker" ? portalText(language, "workerToday") : portalText(language, "customerToday");
  return <div className="portal-shell"><AccountSidebar role={role} badges={badges} /><main className="portal-main"><PortalTopbar name={name} role={role} language={language} /><header className="portal-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="portal-range"><CalendarDays size={14} /> {portalText(language, "liveData")} <PortalRefreshButton language={language} /><ChevronDown size={14} /></div></header>{role === "admin" ? <div className={panel === "requests" ? "admin-dashboard-with-panel" : undefined}><Admin total={total} completed={completed} notices={notices} data={adminData!} language={language} />{panel === "requests" && <AdminRequestsPanel requests={adminPanelRequests} />}</div> : role === "worker" ? <Worker total={total} active={active} completed={completed} unread={unread} requests={requests} notices={notices} rating={workerRating?._avg.rating} ratingCount={workerRating?._count._all} availability={user?.workerProfile?.availability || "OFFLINE"} language={language} /> : <Customer active={active} completed={completed} unread={unread} requests={requests} notices={notices} nearby={nearby} language={language} />}</main></div>;
}

export function PortalTopbar({ name, role, language = "en" }: { name: string; role: Role; language?: string }) { return <header className="portal-topbar">{role !== "worker" && <form className="portal-search" action={role === "customer" ? "/customer/services" : "/admin/users"}><Search size={15} /><input name="q" placeholder={portalText(language, "searchPlaceholder")} aria-label={portalText(language, "searchPortal")} /></form>}<div className="portal-top-actions"><a href={`/${role}/notifications`} aria-label={portalText(language, "notifications")}><Bell size={17} /><i /></a><div className="portal-account-area"><AccountMenu name={name} role={role} language={language} /><PortalRefreshButton language={language} /></div></div></header>; }
function Kpi({ icon, label, value, note, index, href }: { icon: React.ReactNode; label: string; value: string | number; note: string; index: number; href?: string }) { const action = href || (label === "Completed Services" && note === "Verified records" ? "/admin/completed" : ({ "Active Requests": "/customer/requests", "Upcoming Services": "/customer/requests", "Completed Services": "/customer/history", Notifications: "/customer/notifications", "Today's Requests": "/worker/requests", "Active Service": "/worker/active", "Completed This Month": "/worker/completed", "Your Rating": "/worker/reviews" } as Record<string, string>)[label]); return <article className="portal-card"><span className={`portal-icon icon-${index}`}>{icon}</span><div><span>{label}</span><strong>{value}</strong><small><TrendingUp size={11} />{action ? <Link href={action}>{note}</Link> : note}</small></div></article>; }
function Panel({ title, children, action = "View All", href }: { title: string; children: React.ReactNode; action?: string; href?: string }) { return <article className="portal-panel reference-panel"><div className="panel-heading"><h2>{title}</h2>{href ? <a href={href}>{action}</a> : <span>{action}</span>}</div>{children}</article>; }
function Notices({ notices, language = "en" }: { notices: Notice[]; language?: string }) { return <div className="activity-list">{notices.length ? notices.map((notice) => <div key={notice.id}><span className="activity-icon"><CircleAlert size={14} /></span><div><strong>{notice.title}</strong><small>{notice.body}</small></div><time>{dateLabel(notice.createdAt, language)}</time></div>) : <div><span className="activity-icon"><CheckCircle2 size={14} /></span><div><strong>{portalText(language, "noActivityYet")}</strong><small>{portalText(language, "updatesHere")}</small></div></div>}</div>; }
function Requests({ requests, language = "en" }: { requests: RequestRow[]; language?: string }) { return requests.length ? <div className="reference-list">{requests.map((request) => <div className="reference-list-row" key={request.id}><span className="reference-list-icon"><Wrench size={14} /></span><div><strong>{request.service.name}</strong><small>{request.description} · {dateLabel(request.updatedAt, language)}</small></div><span className="status-pill">{request.status.replaceAll("_", " ")}</span></div>)}</div> : <div className="dashboard-empty"><CheckCircle2 size={24} /><strong>{portalText(language, "noServiceRequests")}</strong><span>{portalText(language, "liveRequestsHere")}</span></div>; }
function AdminRequestsPanel({ requests }: { requests: { id: string; status: string; description: string; locationLabel: string | null; updatedAt: Date; service: { name: string }; customer: { fullName: string }; worker: { fullName: string } | null }[] }) { return <aside className="admin-side-panel"><div className="panel-heading"><div><span className="kicker">Admin workspace</span><h2>Service requests</h2></div><Link href="/admin">Close</Link></div>{requests.length ? <div className="workspace-table">{requests.map((request) => <div className="workspace-row" key={request.id}><div><strong>{request.service.name}</strong><small>{request.customer.fullName} · {request.worker?.fullName || "Unassigned"} · {request.locationLabel || "Location private"} · {request.description}</small></div><span className="status-pill">{request.status.replaceAll("_", " ")}</span></div>)}</div> : <div className="dashboard-empty">No service requests found.</div>}</aside>; }

function Admin({ total, completed, notices, data, language }: { total: number; completed: number; notices: Notice[]; data: [number, number, number, { id: string; fullName: string; completedJobs: number; ratingAverage: unknown; availability: string }[]]; language: string }) { const text = (key: "totalCustomers" | "totalWorkers" | "serviceRequests" | "completedServicesCard" | "verifiedRecords" | "userGrowth" | "requestsByCategory" | "monthlyActivity" | "workerPerformance" | "customerEngagement" | "topServices" | "byRequests" | "liveCatalog" | "availableWorkers" | "reportsComplaints" | "recentActivity") => portalText(language, key); const [customers, workers, available, topWorkers] = data; return <><section className="portal-card-grid"><Kpi index={0} icon={<Users size={17} />} label={text("totalCustomers")} value={customers} note="Live database" /><Kpi index={1} icon={<Users size={17} />} label={text("totalWorkers")} value={workers} note={`${available} available now`} /><Kpi index={2} icon={<Wrench size={17} />} label={text("serviceRequests")} value={total} note="Live database" /><Kpi index={3} icon={<CheckCircle2 size={17} />} label={text("completedServicesCard")} value={completed} note={text("verifiedRecords")} /></section><section className="reference-dashboard-grid"><div className="reference-main-column"><div className="reference-three-panels"><Panel title={text("userGrowth")} href="/admin/analytics"><Chart type="line" /></Panel><Panel title={text("requestsByCategory")} href="/admin/requests"><Donut value={total} /></Panel><Panel title={text("monthlyActivity")} href="/admin/analytics"><Chart type="bars" /></Panel></div><div className="reference-two-panels"><Panel title={text("workerPerformance")} href="/admin/users?role=WORKER"><div className="reference-table">{topWorkers.length ? topWorkers.map((worker, index) => <div key={worker.id}><span>{index + 1}</span><strong>{worker.fullName}</strong><small>{worker.completedJobs} jobs</small><small>★ {String(worker.ratingAverage)}</small><em>{worker.availability}</em></div>) : <span>{portalText(language, "noWorkerRecords")}</span>}</div></Panel><Panel title={text("customerEngagement")} href="/admin/users?role=CUSTOMER"><Donut value={completed} label={text("completedServicesCard")} /></Panel></div></div><aside className="portal-rail"><Panel title={text("recentActivity")} href="/admin/audit"><Notices notices={notices} /></Panel><Panel title={text("topServices")} action={text("byRequests")} href="/admin/categories"><div className="ranking-row"><span>1</span><strong>{text("liveCatalog")}</strong><small>{total}</small></div><div className="ranking-row"><span>2</span><strong>{text("availableWorkers")}</strong><small>{available}</small></div></Panel><Panel title={text("reportsComplaints")} href="/admin/reports"><div className="dashboard-empty">Moderated reports will appear here.</div></Panel></aside></section></>; }
function Customer({ active, completed, unread, requests, notices, nearby, language }: { active: number; completed: number; unread: number; requests: RequestRow[]; notices: Notice[]; nearby: { id: string; fullName: string; ratingAverage: unknown; completedJobs: number }[]; language: string }) { const text = (key: "activeRequests" | "upcomingServices" | "completedServicesCard" | "notificationsCard" | "viewAll" | "viewHistory" | "quickBook" | "whatService" | "search" | "nearbyWorkers" | "available" | "recentActivity" | "recentHistory" | "notifications" | "savedWorkersPanel" | "noAvailableWorkers") => portalText(language, key); return <><section className="portal-card-grid"><Kpi index={0} icon={<Wrench size={17} />} label={text("activeRequests")} value={active} note={text("viewAll")} /><Kpi index={1} icon={<CalendarDays size={17} />} label={text("upcomingServices")} value={active} note={text("viewAll")} /><Kpi index={2} icon={<CheckCircle2 size={17} />} label={text("completedServicesCard")} value={completed} note={text("viewHistory")} /><Kpi index={3} icon={<Star size={17} />} label={text("notificationsCard")} value={unread} note={text("viewAll")} /></section><section className="reference-dashboard-grid"><div className="reference-main-column"><div className="reference-three-panels"><Panel title={text("quickBook")} href="/customer/requests"><div className="quick-search reference-book"><Search size={14} /><span>{text("whatService")}</span><MapPin size={14} /><a href="/#services">{text("search")}</a></div></Panel><Panel title={text("nearbyWorkers")} href="/customer/saved"><div className="reference-list">{nearby.length ? nearby.map((worker) => <div className="reference-list-row" key={worker.id}><span className="mini-avatar">{initials(worker.fullName)}</span><div><strong>{worker.fullName}</strong><small>★ {String(worker.ratingAverage)} · {worker.completedJobs} jobs</small></div><span className="status-pill">{text("available")}</span></div>) : <span>{text("noAvailableWorkers")}</span>}</div></Panel><Panel title={text("recentActivity")} href="/customer/notifications"><Notices notices={notices} /></Panel></div><Panel title={text("recentHistory")} href="/customer/history"><Requests requests={requests} /></Panel></div><aside className="portal-rail"><Panel title={text("notifications")} href="/customer/notifications"><Notices notices={notices} /></Panel><Panel title={text("savedWorkersPanel")} href="/customer/saved"><div className="dashboard-empty">{text("savedWorkersPanel")}</div></Panel></aside></section></>; }
function Worker({ total, active, completed, unread, requests, notices, rating, ratingCount, availability, language }: { total: number; active: number; completed: number; unread: number; requests: RequestRow[]; notices: Notice[]; rating?: number | null; ratingCount?: number; availability: string; language: string }) {
  const text = (key: "todaysRequests" | "activeService" | "completedThisMonth" | "yourRating" | "viewAll" | "viewDetails" | "reviewsCount" | "todaysSchedule" | "earningsOverview" | "performance" | "completedServices" | "totalRequests" | "averageRating" | "upcomingRequests" | "recentActivity") => portalText(language, key, key === "reviewsCount" ? { count: ratingCount || 0 } : {});
  return <>
    <AvailabilityToggle initial={availability} language={language} />
    <section className="portal-card-grid">
      <Kpi index={0} icon={<Wrench size={17} />} label={text("todaysRequests")} value={active} note={text("viewAll")} />
      <Kpi index={1} icon={<CircleAlert size={17} />} label={text("activeService")} value={active} note={text("viewDetails")} />
      <Kpi index={2} icon={<CheckCircle2 size={17} />} label={text("completedThisMonth")} value={completed} note={text("viewAll")} />
      <Kpi index={3} icon={<Star size={17} />} label={text("yourRating")} value={rating?.toFixed(1) || "-"} note={text("reviewsCount")} />
    </section>
    <section className="reference-dashboard-grid">
      <div className="reference-main-column">
        <div className="reference-two-panels">
          <Panel title={text("todaysSchedule")} href="/worker/requests"><Requests requests={requests} /></Panel>
          <Panel title={text("earningsOverview")}><WorkerEarningsPanel /></Panel>
        </div>
        <Panel title={text("performance")} href="/worker/analytics"><div className="performance-grid"><div><strong>{completed}</strong><small>{text("completedServices")}</small></div><div><strong>{total}</strong><small>{text("totalRequests")}</small></div><div><strong>{rating?.toFixed(1) || "-"}</strong><small>{text("averageRating")}</small></div></div></Panel>
      </div>
      <aside className="portal-rail"><Panel title={text("upcomingRequests")} href="/worker/requests"><Requests requests={requests.slice(0, 3)} /></Panel><Panel title={text("recentActivity")} href="/worker/notifications"><Notices notices={notices} /></Panel></aside>
    </section>
  </>;
}
function Chart({ type }: { type: "line" | "bars" }) { return <div className={`reference-chart ${type}`}>{[1, 2, 3, 4, 5, 6].map((item) => <b key={item} />)}</div>; }
function Donut({ value, label = "Total Requests" }: { value: number; label?: string }) { return <div className="reference-donut"><strong>{value}</strong><small>{label}</small></div>; }
