import { Bell, CalendarDays, CheckCircle2, ChevronDown, CircleAlert, MapPin, Search, Star, TrendingUp, Users, Wrench } from "lucide-react";
import { AccountSidebar } from "./AccountSidebar";
import { prisma } from "@/lib/prisma";
import { requireSession, type AppRole } from "@/lib/auth";
import { AvailabilityToggle } from "./AvailabilityToggle";
import { AccountMenu } from "./AccountMenu";
import { PortalRefreshButton } from "./PortalRefreshButton";
import { getSidebarBadges } from "@/lib/sidebar-badges";

type Role = "customer" | "worker" | "admin";
type RequestRow = { id: string; status: string; description: string; service: { name: string }; updatedAt: Date };
type Notice = { id: string; title: string; body: string; createdAt: Date };

const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
const dateLabel = (date: Date) => new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short" }).format(date);

export async function PortalDashboard({ role }: { role: Role }) {
  const session = await requireSession([role.toUpperCase() as AppRole]);
    const badges = await getSidebarBadges(session.role, session.userId);
  const user = await prisma.user.findUnique({ where: { id: session.userId }, include: { customerProfile: true, workerProfile: true } });
  const name = role === "admin" ? user?.displayName || user?.email.split("@")[0] || "Administrator" : role === "worker" ? user?.workerProfile?.fullName || "Worker account" : user?.customerProfile?.fullName || "Customer account";
  const scope = role === "admin" ? {} : role === "customer" ? { customer: { userId: session.userId } } : { worker: { userId: session.userId } };
  const [total, active, completed, unread, requests, notices] = await Promise.all([
    prisma.serviceRequest.count({ where: scope }),
    prisma.serviceRequest.count({ where: { ...scope, status: { in: ["SUBMITTED", "SENT", "ACCEPTED", "SCHEDULED", "EN_ROUTE", "IN_PROGRESS"] } } }),
    prisma.serviceRequest.count({ where: { ...scope, status: "COMPLETED" } }),
    prisma.notification.count({ where: { userId: session.userId, readAt: null } }),
    prisma.serviceRequest.findMany({ where: scope, select: { id: true, status: true, description: true, service: { select: { name: true } }, updatedAt: true }, orderBy: { updatedAt: "desc" }, take: 6 }),
    prisma.notification.findMany({ where: { userId: session.userId }, orderBy: { createdAt: "desc" }, take: 5, select: { id: true, title: true, body: true, createdAt: true } }),
  ]);
  const adminData = role === "admin" ? await Promise.all([prisma.user.count({ where: { role: "CUSTOMER", status: "ACTIVE" } }), prisma.user.count({ where: { role: "WORKER", status: "ACTIVE" } }), prisma.workerProfile.count({ where: { availability: "AVAILABLE", user: { status: "ACTIVE" } } }), prisma.workerProfile.findMany({ where: { user: { status: "ACTIVE" } }, orderBy: { completedJobs: "desc" }, take: 5, select: { id: true, fullName: true, completedJobs: true, ratingAverage: true, availability: true } })]) : null;
  const workerRating = role === "worker" ? await prisma.review.aggregate({ where: { worker: { userId: session.userId } }, _avg: { rating: true }, _count: { _all: true } }) : null;
  const nearby = role === "customer" ? await prisma.workerProfile.findMany({ where: { availability: "AVAILABLE", user: { status: "ACTIVE" } }, orderBy: { ratingAverage: "desc" }, take: 3, select: { id: true, fullName: true, ratingAverage: true, completedJobs: true } }) : [];
  const title = role === "admin" ? "Admin Dashboard" : role === "worker" ? `Good Morning, ${name}!` : `Welcome back, ${name}!`;
  const subtitle = role === "admin" ? "Platform overview and key metrics" : role === "worker" ? "Here is what is happening with your services today." : "Find the right service, right when you need it.";
  return <div className="portal-shell"><AccountSidebar role={role} badges={badges} /><main className="portal-main"><PortalTopbar name={name} role={role} /><header className="portal-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="portal-range"><CalendarDays size={14} /> Live data <ChevronDown size={14} /></div></header>{role === "admin" ? <Admin total={total} completed={completed} notices={notices} data={adminData!} /> : role === "worker" ? <Worker total={total} active={active} completed={completed} unread={unread} requests={requests} notices={notices} rating={workerRating?._avg.rating} ratingCount={workerRating?._count._all} availability={user?.workerProfile?.availability || "OFFLINE"} /> : <Customer active={active} completed={completed} unread={unread} requests={requests} notices={notices} nearby={nearby} />}</main></div>;
}

export function PortalTopbar({ name, role }: { name: string; role: Role }) { return <header className="portal-topbar"><form className="portal-search" action={role === "customer" ? "/customer/services" : role === "worker" ? "/worker/services" : "/admin/users"}><Search size={15} /><input name="q" placeholder="Search users, workers, services..." aria-label="Search portal" /></form><div className="portal-top-actions"><a href={`/${role}/notifications`} aria-label="Notifications"><Bell size={17} /><i /></a><div className="portal-account-area"><AccountMenu name={name} role={role} /><PortalRefreshButton /></div></div></header>; }
function Kpi({ icon, label, value, note, index, href }: { icon: React.ReactNode; label: string; value: string | number; note: string; index: number; href?: string }) { const action = href || (label === "Completed Services" && note === "Verified records" ? "/admin/completed" : ({ "Active Requests": "/customer/requests", "Upcoming Services": "/customer/requests", "Completed Services": "/customer/history", Notifications: "/customer/notifications", "Today's Requests": "/worker/requests", "Active Service": "/worker/active", "Completed This Month": "/worker/completed", "Your Rating": "/worker/reviews" } as Record<string, string>)[label]); return <article className="portal-card"><span className={`portal-icon icon-${index}`}>{icon}</span><div><span>{label}</span><strong>{value}</strong><small><TrendingUp size={11} />{action ? <a href={action}>{note}</a> : note}</small></div></article>; }
function Panel({ title, children, action = "View All", href }: { title: string; children: React.ReactNode; action?: string; href?: string }) { return <article className="portal-panel reference-panel"><div className="panel-heading"><h2>{title}</h2>{href ? <a href={href}>{action}</a> : <span>{action}</span>}</div>{children}</article>; }
function Notices({ notices }: { notices: Notice[] }) { return <div className="activity-list">{notices.length ? notices.map((notice) => <div key={notice.id}><span className="activity-icon"><CircleAlert size={14} /></span><div><strong>{notice.title}</strong><small>{notice.body}</small></div><time>{dateLabel(notice.createdAt)}</time></div>) : <div><span className="activity-icon"><CheckCircle2 size={14} /></span><div><strong>No activity yet</strong><small>New updates appear here.</small></div></div>}</div>; }
function Requests({ requests }: { requests: RequestRow[] }) { return requests.length ? <div className="reference-list">{requests.map((request) => <div className="reference-list-row" key={request.id}><span className="reference-list-icon"><Wrench size={14} /></span><div><strong>{request.service.name}</strong><small>{request.description} · {dateLabel(request.updatedAt)}</small></div><span className="status-pill">{request.status.replaceAll("_", " ")}</span></div>)}</div> : <div className="dashboard-empty"><CheckCircle2 size={24} /><strong>No service requests yet</strong><span>Live requests will appear here.</span></div>; }

function Admin({ total, completed, notices, data }: { total: number; completed: number; notices: Notice[]; data: [number, number, number, { id: string; fullName: string; completedJobs: number; ratingAverage: unknown; availability: string }[]] }) { const [customers, workers, available, topWorkers] = data; return <><section className="portal-card-grid"><Kpi index={0} icon={<Users size={17} />} label="Total Customers" value={customers} note="Live database" /><Kpi index={1} icon={<Users size={17} />} label="Total Workers" value={workers} note={`${available} available now`} /><Kpi index={2} icon={<Wrench size={17} />} label="Service Requests" value={total} note="Live database" /><Kpi index={3} icon={<CheckCircle2 size={17} />} label="Completed Services" value={completed} note="Verified records" /></section><section className="reference-dashboard-grid"><div className="reference-main-column"><div className="reference-three-panels"><Panel title="User Growth" href="/admin/analytics"><Chart type="line" /></Panel><Panel title="Service Requests by Category" href="/admin/requests"><Donut value={total} /></Panel><Panel title="Monthly Activity" href="/admin/analytics"><Chart type="bars" /></Panel></div><div className="reference-two-panels"><Panel title="Worker Performance" href="/admin/workers"><div className="reference-table">{topWorkers.length ? topWorkers.map((worker, index) => <div key={worker.id}><span>{index + 1}</span><strong>{worker.fullName}</strong><small>{worker.completedJobs} jobs</small><small>★ {String(worker.ratingAverage)}</small><em>{worker.availability}</em></div>) : <span>No worker records yet.</span>}</div></Panel><Panel title="Customer Engagement" href="/admin/users"><Donut value={completed} label="Completed services" /></Panel></div></div><aside className="portal-rail"><Panel title="Recent Activity" href="/admin/audit"><Notices notices={notices} /></Panel><Panel title="Top Services" action="By requests" href="/admin/categories"><div className="ranking-row"><span>1</span><strong>Live service catalog</strong><small>{total}</small></div><div className="ranking-row"><span>2</span><strong>Available workers</strong><small>{available}</small></div></Panel><Panel title="Recent Reports & Complaints" href="/admin/reports"><div className="dashboard-empty">Moderated reports will appear here.</div></Panel></aside></section></>; }
function Customer({ active, completed, unread, requests, notices, nearby }: { active: number; completed: number; unread: number; requests: RequestRow[]; notices: Notice[]; nearby: { id: string; fullName: string; ratingAverage: unknown; completedJobs: number }[] }) { return <><section className="portal-card-grid"><Kpi index={0} icon={<Wrench size={17} />} label="Active Requests" value={active} note="View all" /><Kpi index={1} icon={<CalendarDays size={17} />} label="Upcoming Services" value={active} note="View all" /><Kpi index={2} icon={<CheckCircle2 size={17} />} label="Completed Services" value={completed} note="View history" /><Kpi index={3} icon={<Star size={17} />} label="Notifications" value={unread} note="View all" /></section><section className="reference-dashboard-grid"><div className="reference-main-column"><div className="reference-three-panels"><Panel title="Quick Book Service" href="/customer/requests"><div className="quick-search reference-book"><Search size={14} /><span>What service do you need?</span><MapPin size={14} /><a href="/#services">Search</a></div></Panel><Panel title="Nearby Workers" href="/customer/saved"><div className="reference-list">{nearby.length ? nearby.map((worker) => <div className="reference-list-row" key={worker.id}><span className="mini-avatar">{initials(worker.fullName)}</span><div><strong>{worker.fullName}</strong><small>★ {String(worker.ratingAverage)} · {worker.completedJobs} jobs</small></div><span className="status-pill">Available</span></div>) : <span>No available workers yet.</span>}</div></Panel><Panel title="Recent Activity" href="/customer/notifications"><Notices notices={notices} /></Panel></div><Panel title="Recent Service History" href="/customer/history"><Requests requests={requests} /></Panel></div><aside className="portal-rail"><Panel title="Notifications" href="/customer/notifications"><Notices notices={notices} /></Panel><Panel title="Saved Workers" href="/customer/saved"><div className="dashboard-empty">Saved workers will appear here.</div></Panel></aside></section></>; }
function Worker({ total, active, completed, unread, requests, notices, rating, ratingCount, availability }: { total: number; active: number; completed: number; unread: number; requests: RequestRow[]; notices: Notice[]; rating?: number | null; ratingCount?: number; availability: string }) { return <><AvailabilityToggle initial={availability} /><section className="portal-card-grid"><Kpi index={0} icon={<Wrench size={17} />} label="Today's Requests" value={active} note="View all" /><Kpi index={1} icon={<CircleAlert size={17} />} label="Active Service" value={active} note="View details" /><Kpi index={2} icon={<CheckCircle2 size={17} />} label="Completed This Month" value={completed} note="View all" /><Kpi index={3} icon={<Star size={17} />} label="Your Rating" value={rating?.toFixed(1) || "-"} note={`${ratingCount || 0} reviews`} /></section><section className="reference-dashboard-grid"><div className="reference-main-column"><div className="reference-two-panels"><Panel title="Today's Schedule" href="/worker/requests"><Requests requests={requests} /></Panel><Panel title="Earnings Overview"><div className="earnings-total">₹{completed ? completed * 500 : 0}</div><small>Based on completed services</small><Chart type="bars" /></Panel></div><Panel title="Performance" href="/worker/analytics"><div className="performance-grid"><div><strong>{completed}</strong><small>Completed services</small></div><div><strong>{total}</strong><small>Total requests</small></div><div><strong>{rating?.toFixed(1) || "-"}</strong><small>Average rating</small></div></div></Panel></div><aside className="portal-rail"><Panel title="Upcoming Requests" href="/worker/requests"><Requests requests={requests.slice(0, 3)} /></Panel><Panel title="Recent Activity" href="/worker/notifications"><Notices notices={notices} /></Panel></aside></section></>; }
function Chart({ type }: { type: "line" | "bars" }) { return <div className={`reference-chart ${type}`}>{[1, 2, 3, 4, 5, 6].map((item) => <b key={item} />)}</div>; }
function Donut({ value, label = "Total Requests" }: { value: number; label?: string }) { return <div className="reference-donut"><strong>{value}</strong><small>{label}</small></div>; }
