import Link from "next/link";
import { notFound } from "next/navigation";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function AdminUserDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSession(["ADMIN"]);
  const { id } = await params;
  const user = await prisma.user.findFirst({ where: { id, role: { in: ["CUSTOMER", "WORKER"] } }, include: { customerProfile: { include: { requests: { include: { service: true, worker: true }, orderBy: { createdAt: "desc" }, take: 100 } } }, workerProfile: { include: { requests: { include: { service: true, customer: true }, orderBy: { createdAt: "desc" }, take: 100 } } }, addresses: true, reviews: true, receivedReports: true, _count: { select: { sessions: true, conversationMemberships: true, auditEvents: true, savedWorkers: true, locationEvents: true, financialEntries: true, fraudSignals: true } } } });
  if (!user) notFound();
  const requests = user.customerProfile?.requests || user.workerProfile?.requests || [];
  const counts = requests.reduce<Record<string, number>>((result, request) => ({ ...result, [request.status]: (result[request.status] || 0) + 1 }), {});
  const locations = new Set(requests.map((request) => request.locationLabel).filter(Boolean));
  const [uploadedFiles, auditHistory] = await Promise.all([prisma.fileAsset.count({ where: { ownerId: user.id } }), prisma.auditLog.findMany({ where: { targetId: user.id }, orderBy: { createdAt: "desc" }, take: 50, select: { id: true, action: true, targetType: true, createdAt: true } })]);
  const name = user.displayName || user.customerProfile?.fullName || user.workerProfile?.fullName || user.email;
  return <main className="state-page"><section className="state-panel" style={{ maxWidth: 1100, textAlign: "left" }}><Link className="back-link" href="/admin/users">Users</Link><span className="kicker">Selected account</span><h1>{name}</h1><p>{user.email} · {user.role} · {user.status}</p><div className="workspace-stats"><div><strong>{requests.length}</strong><span>Total requests</span></div>{["SUBMITTED", "ACCEPTED", "REJECTED", "CANCELLED", "DISPUTED", "COMPLETED"].map((status) => <div key={status}><strong>{counts[status] || 0}</strong><span>{status}</span></div>)}<div><strong>{locations.size}</strong><span>Service locations</span></div><div><strong>{user.addresses.length}</strong><span>Saved addresses</span></div><div><strong>{uploadedFiles}</strong><span>Uploaded files</span></div></div>{user.workerProfile && <div className="profile-details"><h2>Worker performance</h2><p>Verification: {user.workerProfile.verificationStatus} · Availability: {user.workerProfile.availability} · Completed jobs: {user.workerProfile.completedJobs} · Rating: {user.workerProfile.ratingAverage.toString()} ({user.workerProfile.ratingCount})</p><p>Radius: {user.workerProfile.serviceRadiusKm?.toString() || "Not set"} km · Current location: {user.workerProfile.latitude && user.workerProfile.longitude ? "Stored with consent policy" : "Not set"}</p></div>}<div className="profile-details"><h2>Activity and privacy summary</h2><p>Reviews: {user.reviews.length} · Reports received: {user.receivedReports.length} · Conversations: {user._count.conversationMemberships} · Audit events: {user._count.auditEvents} · Financial entries: {user._count.financialEntries} · Fraud signals: {user._count.fraudSignals} · Historical location events: {user._count.locationEvents}</p></div><div className="profile-details"><h2>Audit history</h2>{auditHistory.length ? auditHistory.map((entry) => <p key={entry.id}>{entry.action} · {entry.targetType} · {entry.createdAt.toLocaleString("en-IN")}</p>) : <p>No audit events recorded for this account.</p>}</div><div className="workspace-table">{requests.map((request) => <div className="workspace-row" key={request.id}><div><strong>{request.service.name}</strong><small>{request.description} · {request.locationLabel || "Location private"} · {request.createdAt.toLocaleDateString("en-IN")}</small></div><span className="status-pill">{request.status}</span></div>)}</div></section></main>;
}
